tracks:
    - id: 1
      name: My Gene Models Track
      type: ModelsTrack
      path: Gene Models
      data: /features/annoj/11
      showControls: true
      height: 80
    # - id: 2
    #   name: Reads from an RDBMS provided experiment loaded via gff
    #   type: ReadsTrack
    #   path: Reads
    #   data: /features/annoj/2
    #   showControls: true
    #   minHeight: 20
    #   maxHeight: 500
    #   height: 70
#A list of tracks that will be active by default (use the ID of the track)
active:
    - 1
    - 2
#genome - the service that knows about the genome
genome: genomes/annoj/1
# bookmarks - the service that keeps the bookmarks
bookmarks: 
#css - a list of services or locations for css (optional)
stylesheets: 
      - id: simple
        name: simple CSS
        href: stylesheets/simple.css
        active: true
#where to focus the view on start up
location:
    assembly: Chr1
    position: 4000
    bases: 20
    pixels: 1
#site administrator information (optional)    
admin:
    name: 'Mick Jagger'
    email: 'Mick@streetfightingman.ac.uk'
    notes: 'moves well'
    citation: 'a reference'
